# Indices

In [1]:
import numpy as np

In [2]:
numeros = np.arange(11)**2

In [3]:
numeros

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [4]:
indices = [2,5,7]

In [5]:
numeros[indices]

array([ 4, 25, 49])

In [7]:
arreglo_frutas = np.array([
    ['Piña','Manzana','Pera','Melon'],
    ['Pera','Uva','Naranja','Papaya'],
    ['Frutilla','Platano','Granadilla','Sandia']
])

In [8]:
arreglo_frutas.shape

(3, 4)

In [13]:
arreglo_filas = np.array([
    [0,0],
    [1,1],
    [2,2],
])

In [14]:
arreglo_columnas = np.array([
    [1,3],
    [1,2],
    [0,2],
])

In [15]:
arreglo_frutas[arreglo_filas,arreglo_columnas]

array([['Manzana', 'Melon'],
       ['Uva', 'Naranja'],
       ['Frutilla', 'Granadilla']], dtype='<U10')

In [16]:
arreglo_frutas

array([['Piña', 'Manzana', 'Pera', 'Melon'],
       ['Pera', 'Uva', 'Naranja', 'Papaya'],
       ['Frutilla', 'Platano', 'Granadilla', 'Sandia']], dtype='<U10')

In [27]:
arreglo_frutas_3d = np.array([
    'Piña','Manzana','Pera','Melon'
    'Pera','Uva','Naranja','Papaya'
    'Frutilla','Platano','Granadilla','Sandia',
    'Piña Shiny','Manzana Shiny','Pera Shiny','Melon Shiny'
    'Pera Shiny','Uva Shiny','Naranja Shiny','Papaya Shiny'
    'Frutilla Shiny','Platano Shiny','Granadilla Shiny','Sandia Shiny',
    'Granada','Granada Shiny','Taxo Shiny','Taxo'
]).reshape(3,4,2)

In [28]:
arreglo_frutas_3d

array([[['Piña', 'Manzana'],
        ['Pera', 'MelonPera'],
        ['Uva', 'Naranja'],
        ['PapayaFrutilla', 'Platano']],

       [['Granadilla', 'Sandia'],
        ['Piña Shiny', 'Manzana Shiny'],
        ['Pera Shiny', 'Melon ShinyPera Shiny'],
        ['Uva Shiny', 'Naranja Shiny']],

       [['Papaya ShinyFrutilla Shiny', 'Platano Shiny'],
        ['Granadilla Shiny', 'Sandia Shiny'],
        ['Granada', 'Granada Shiny'],
        ['Taxo Shiny', 'Taxo']]], dtype='<U26')

In [29]:
arreglo_frutas_3d.shape

(3, 4, 2)

In [33]:
arreglo_frutas_3d[0][0][0]

'Piña'

In [34]:
arreglo_frutas[0][0]

'Piña'

In [37]:
arreglo_frutas[np.array([0]),np.array([0])]

array(['Piña'], dtype='<U10')

In [38]:
arreglo_frutas[np.array([0,0]),np.array([0,1])]

array(['Piña', 'Manzana'], dtype='<U10')

In [41]:
arreglo_frutas_3d[np.array([0,0]),np.array([0,0]),np.array([0,1])]

array(['Piña', 'Manzana'], dtype='<U26')

In [43]:
arreglo_frutas_3d[np.array([0]),np.array([0]),np.array([0])]

array(['Piña'], dtype='<U26')

In [42]:
arreglo_frutas_3d[np.array([0]),np.array([0]),np.array([1])]

array(['Manzana'], dtype='<U26')

In [67]:
primera_dimension = np.array(
    [0,0,0]
)

In [68]:
segunda_dimension = np.array(
    [0,0,0]
)

In [69]:
tercera_dimension = np.array(
    [0,1,0]
)

In [70]:
arreglo_frutas_3d[primera_dimension, segunda_dimension, tercera_dimension]

array(['Piña', 'Manzana', 'Piña'], dtype='<U26')

In [73]:
arreglo_frutas_3d[primera_dimension, segunda_dimension, tercera_dimension] = 2

In [74]:
arreglo_frutas_3d

array([[['2', '2'],
        ['Pera', 'MelonPera'],
        ['Uva', 'Naranja'],
        ['PapayaFrutilla', 'Platano']],

       [['Granadilla', 'Sandia'],
        ['Piña Shiny', 'Manzana Shiny'],
        ['Pera Shiny', 'Melon ShinyPera Shiny'],
        ['Uva Shiny', 'Naranja Shiny']],

       [['Papaya ShinyFrutilla Shiny', 'Platano Shiny'],
        ['Granadilla Shiny', 'Sandia Shiny'],
        ['Granada', 'Granada Shiny'],
        ['Taxo Shiny', 'Taxo']]], dtype='<U26')

In [75]:
arreglo_diez = np.arange(10)

In [78]:
arreglo_mayor_a_cinco = arreglo_diez > 5

In [79]:
arreglo_diez[arreglo_mayor_a_cinco]

array([6, 7, 8, 9])